# NumPy и pandas: числа и таблицы в Python

Представьте список оценок всех учеников школы — несколько тысяч чисел. Считать средний балл вручную
долго, а писать для каждого вопроса свой цикл `for` — громоздко. Для таких задач в Python есть две
библиотеки:

- **NumPy** — для больших наборов чисел: сложить, умножить, найти среднее одной командой;
- **pandas** — для таблиц, похожих на Excel: выбрать строки и столбцы, отсортировать, посчитать по группам.

После этого занятия вы сможете загрузить таблицу, выбрать нужные строки и столбцы, посчитать простую
статистику, заполнить пропуски и получить ответ на вопрос по данным.

In [1]:
import numpy as np
import pandas as pd

`np` и `pd` — короткие имена библиотек. Так пишут почти во всех примерах на Python, поэтому и мы
будем писать `np.array`, а не `numpy.array`.

## NumPy: массивы чисел

### Массив — коробка с числами

Массив — это удобная коробка с числами. В неё складывают числа одного вида, и дальше с ними работают
все сразу. Массив создают из обычного списка командой `np.array`.

In [2]:
scores = np.array([72, 85, 90, 64])
print(scores)
print(type(scores))

[72 85 90 64]
<class 'numpy.ndarray'>

### Чем массив отличается от списка

Список и массив ведут себя по-разному. Если умножить список на 2, он повторится два раза. Если
умножить массив на 2, удвоится каждое число — именно это обычно и нужно, когда работаешь с оценками
или ценами.

In [3]:
numbers = [1, 2, 3]
print(numbers * 2)            # список повторился

array = np.array([1, 2, 3])
print(array * 2)              # каждое число умножилось

[1, 2, 3, 1, 2, 3]
[2 4 6]

### Создание чисел

Числа не всегда набирают вручную. `np.arange(start, stop)` даёт числа от `start` до `stop`, не включая
`stop` — как знакомый `range`. `np.linspace(start, stop, n)` делит отрезок на `n` точек, включая оба
конца. `np.zeros(n)` и `np.ones(n)` создают `n` нулей или единиц — удобная заготовка, которую потом
заполняют.

In [4]:
print(np.arange(0, 10))        # 0, 1, ..., 9
print(np.arange(5, 8))
print(np.linspace(0, 1, 5))    # 5 точек от 0 до 1 включительно
print(np.zeros(4))
print(np.ones(3))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0. 0.]
[1. 1. 1.]

### Размер и форма

`size` — сколько всего чисел в массиве. `shape` — форма: для обычного массива это `(число элементов,)`,
а для таблицы чисел — `(строки, столбцы)`.

In [5]:
scores = np.array([72, 85, 90, 64])
print(scores.size, scores.shape)

table = np.array([[90, 80],
                  [70, 60],
                  [85, 95]])
print(table.size, table.shape)     # 6 чисел: 3 строки и 2 столбца

4 (4,)
6 (3, 2)

### Индексы и срезы

Элементы нумеруются с нуля, как в списке. `a[0]` — первый, `a[-1]` — последний, `a[1:4]` — элементы
с номерами 1, 2, 3 (четвёртый не входит). В двумерном массиве указывают строку и столбец через запятую:
`matrix[0, 1]` — строка 0, столбец 1. А `matrix[0]` — вся первая строка.

In [6]:
scores = np.array([72, 85, 90, 64, 58])
print(scores[0], scores[-1])
print(scores[1:4])

matrix = np.array([[90, 80, 70],
                   [65, 75, 85]])
print(matrix[0, 1])      # строка 0, столбец 1
print(matrix[1])         # вся вторая строка

72 58
[85 90 64]
80
[65 75 85]

### Действия со всеми числами сразу

Арифметика применяется к каждому числу массива. Прибавить 5 ко всем оценкам — просто `scores + 5`.
Два массива одинаковой длины складываются поэлементно: первое число с первым, второе со вторым.

In [7]:
scores = np.array([72, 85, 90, 64])
print(scores + 5)
print(scores - 10)
print(scores * 2)
print(scores / 100)
print(scores ** 2)

bonus = np.array([3, 0, 5, 10])
print(scores + bonus)    # поэлементно: 72+3, 85+0, 90+5, 64+10

[77 90 95 69]
[62 75 80 54]
[144 170 180 128]
[0.72 0.85 0.9  0.64]
[5184 7225 8100 4096]
[75 85 95 74]

### Частые функции

Для всего массива сразу: `np.sum` — сумма, `np.mean` — среднее, `np.min` и `np.max` — наименьшее
и наибольшее число, `np.round(a, 1)` — округлить каждое число до одного знака после точки.

In [8]:
scores = np.array([72, 85, 90, 64])
print(np.sum(scores))
print(np.mean(scores))
print(np.min(scores), np.max(scores))
print(np.round(scores / 3, 1))

311
77.75
64 90
[24.  28.3 30.  21.3]

### Условия и маски

Сравнение с числом тоже применяется ко всем элементам. `scores >= 70` даёт массив из `True` и `False` —
его называют **маской**. Если поставить маску в квадратные скобки, останутся только те числа, где стоит
`True`. А `np.sum(маска)` считает, сколько там `True`: при сложении `True` считается за 1.

In [9]:
scores = np.array([72, 85, 90, 64, 58])
mask = scores >= 70
print(mask)
print(scores[mask])
print(scores[scores >= 70])      # то же самое, но короче
print(np.sum(scores >= 70))      # сколько оценок не ниже 70

[ True  True  True False False]
[72 85 90]
[72 85 90]
3

### Двумерный массив и `axis`

Пусть в строках — ученики, а в столбцах — предметы. `np.mean(table)` даст одно число — среднее по всем
клеткам. Чтобы получить среднее **по каждому предмету**, нужно пройти по строкам сверху вниз и получить
по числу на каждый столбец — это `axis=0`. Чтобы получить среднее **по каждому ученику**, идём по строке
слева направо — это `axis=1`.

Как запомнить: `axis=0` — ответ длиной в число столбцов, `axis=1` — в число строк.

In [10]:
#                 математика  python
table = np.array([[90, 80],     # Аня
                  [70, 60],     # Боря
                  [85, 95]])    # Вера
print(np.mean(table))             # одно число — среднее по всем клеткам
print(np.mean(table, axis=0))     # по предметам: столбец за столбцом
print(np.mean(table, axis=1))     # по ученикам: строка за строкой
print(np.max(table, axis=0))      # лучший балл по каждому предмету

80.0
[81.66666667 78.33333333]
[85. 65. 90.]
[90 95]

## pandas: таблицы

`DataFrame` — это таблица, как лист в Excel: у неё есть столбцы с названиями и строки с номерами.
Разница в том, что таблицей управляют командами Python, а не мышкой. Один столбец таблицы называется
`Series`.

Данные обычно лежат в файле CSV — это обычный текст, где значения в строке разделены запятыми.
В папке `data` лежит файл `students.csv` с данными 1200 школьников: номер, имя, класс, город, баллы
по математике и Python и часы занятий в неделю. Загружаем его командой `pd.read_csv`.

In [11]:
df = pd.read_csv("data/students.csv")
df.head()

,student_id,name,grade,city,math_score,python_score,hours_per_week
0,1,Рита Соколов,11,Санкт-Петербург,66.0,83.0,15
1,2,Маша Семёнов,11,Новосибирск,42.0,61.0,4
2,3,София Лебедев,10,Пермь,80.0,89.0,14
3,4,Оля Голубев,7,Новосибирск,64.0,58.0,3
4,5,Оля Семёнов,9,Казань,NaN,93.0,15

### Просмотр таблицы

`head()` показывает первые пять строк — большие таблицы целиком лучше не печатать. `shape` — размер:
(строк, столбцов). `columns` — названия столбцов. `info()` рассказывает про каждый столбец: сколько
в нём заполненных значений и какого они типа. `describe()` считает статистику по числовым столбцам:
среднее, минимум, максимум.

In [12]:
print(df.shape)
print(df.columns)

(1200, 7)
Index(['student_id', 'name', 'grade', 'city', 'math_score', 'python_score',
       'hours_per_week'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      1200 non-null   int64
 1   name            1200 non-null   str
 2   grade           1200 non-null   int64
 3   city            1200 non-null   str
 4   math_score      1167 non-null   float64
 5   python_score    1156 non-null   float64
 6   hours_per_week  1200 non-null   int64
dtypes: float64(2), int64(3), str(2)
memory usage: 65.8 KB

In [14]:
df.describe().round(1)

       student_id   grade  math_score  python_score  hours_per_week
count      1200.0  1200.0      1167.0        1156.0          1200.0
mean        600.5     9.0        65.1          67.9             8.0
std         346.6     1.4        16.8          16.4             4.3
min           1.0     7.0        12.0          20.0             1.0
25%         300.8     8.0        54.0          57.0             4.0
50%         600.5     9.0        66.0          68.0             8.0
75%         900.2    10.0        76.0          80.0            12.0
max        1200.0    11.0       100.0         100.0            15.0

### Выбор столбца

Один столбец — его имя в квадратных скобках: `df["math_score"]`. Получится `Series`, у которого есть
свои команды: `.mean()`, `.max()`, `.head()` и другие. Несколько столбцов — список имён внутри скобок,
поэтому скобки получаются двойные: `df[["name", "math_score"]]`.

In [15]:
print(df["math_score"].head())
print("средний балл по математике:", round(df["math_score"].mean(), 1))

0    66.0
1    42.0
2    80.0
3    64.0
4     NaN
Name: math_score, dtype: float64
средний балл по математике: 65.1

In [16]:
df[["name", "math_score", "python_score"]].head()

            name  math_score  python_score
0   Рита Соколов        66.0          83.0
1   Маша Семёнов        42.0          61.0
2  София Лебедев        80.0          89.0
3    Оля Голубев        64.0          58.0
4    Оля Семёнов         NaN          93.0

### Выбор строк: `iloc` и `loc`

`iloc` выбирает строки **по номеру**: `df.iloc[0]` — первая строка, `df.iloc[0:3]` — первые три.

`loc` выбирает **по метке строки и имени столбца**: `df.loc[2, "name"]` — имя из строки с меткой 2.
Чаще всего `loc` используют с условием: `df.loc[df["city"] == "Казань", ["name", "city"]]` — строки,
где город Казань, и только два столбца из них.

In [17]:
print(df.iloc[0])                 # первая строка целиком
df.iloc[0:3]

student_id                      1
name                 Рита Соколов
grade                          11
city              Санкт-Петербург
math_score                   66.0
python_score                 83.0
hours_per_week                 15
Name: 0, dtype: object

,student_id,name,grade,city,math_score,python_score,hours_per_week
0,1,Рита Соколов,11,Санкт-Петербург,66.0,83.0,15
1,2,Маша Семёнов,11,Новосибирск,42.0,61.0,4
2,3,София Лебедев,10,Пермь,80.0,89.0,14

In [18]:
print(df.loc[2, "name"])
df.loc[df["city"] == "Казань", ["name", "city", "math_score"]].head()

София Лебедев

             name    city  math_score
4     Оля Семёнов  Казань         NaN
10   Даша Фёдоров  Казань        72.0
12    Гоша Козлов  Казань        88.0
15  Федя Михайлов  Казань        73.0
18     Оля Петров  Казань        44.0

### Фильтрация

Условие на столбец даёт маску — столбец из `True` и `False`, как в NumPy. Маска в квадратных скобках
оставляет только нужные строки. Два условия соединяют знаком `&` («и»), и **каждое условие берут
в скобки** — без скобок Python прочитает запись неправильно.

In [19]:
moscow = df[df["city"] == "Москва"]
print(moscow.shape)
moscow.head()

(360, 7)

,student_id,name,grade,city,math_score,python_score,hours_per_week
13,14,Полина Соколов,8,Москва,69.0,68.0,10
14,15,Юля Иванов,11,Москва,47.0,53.0,3
19,20,Кирилл Новиков,8,Москва,59.0,41.0,2
21,22,Егор Петров,7,Москва,32.0,34.0,7
22,23,Оля Иванов,9,Москва,43.0,52.0,6

In [20]:
strong = df[(df["grade"] == 11) & (df["math_score"] >= 80)]
print("одиннадцатиклассников с математикой от 80:", len(strong))
strong.head()

одиннадцатиклассников с математикой от 80: 63

,student_id,name,grade,city,math_score,python_score,hours_per_week
9,10,Иван Виноградов,11,Тверь,91.0,88.0,11
30,31,Гоша Семёнов,11,Санкт-Петербург,83.0,85.0,13
38,39,Рита Зайцев,11,Санкт-Петербург,82.0,86.0,3
60,61,Женя Попов,11,Москва,89.0,72.0,8
75,76,Артём Фёдоров,11,Москва,82.0,82.0,6

### Новый столбец

Новый столбец создают присваиванием: имя в квадратных скобках слева, значения справа. Средний балл
по двум предметам — `df[["math_score", "python_score"]].mean(axis=1)`: среднее по каждой строке.
Если один из баллов пропущен, pandas не считает пропуск нулём — средним станет оставшийся балл.

In [21]:
df["average_score"] = df[["math_score", "python_score"]].mean(axis=1)
df[["name", "math_score", "python_score", "average_score"]].head()

            name  math_score  python_score  average_score
0   Рита Соколов        66.0          83.0           74.5
1   Маша Семёнов        42.0          61.0           51.5
2  София Лебедев        80.0          89.0           84.5
3    Оля Голубев        64.0          58.0           61.0
4    Оля Семёнов         NaN          93.0           93.0

### Сортировка

`sort_values("столбец")` сортирует по возрастанию, а с `ascending=False` — по убыванию. Исходная
таблица при этом не меняется: результат — новая таблица, которую можно сохранить в переменную.

In [22]:
df.sort_values("python_score", ascending=False).head()

,student_id,name,grade,city,math_score,python_score,hours_per_week,average_score
895,896,Катя Смирнов,7,Санкт-Петербург,87.0,100.0,15,93.5
389,390,Вера Кузнецов,10,Тверь,93.0,100.0,6,96.5
352,353,Гоша Виноградов,9,Санкт-Петербург,100.0,100.0,14,100.0
104,105,Даша Иванов,8,Казань,90.0,100.0,15,95.0
191,192,Гоша Павлов,9,Пермь,78.0,100.0,15,89.0

### Подсчёт категорий

`value_counts()` считает, сколько раз встречается каждое значение в столбце. Так узнают, сколько
учеников из каждого города или в каждом классе.

In [23]:
print(df["city"].value_counts())
print(df["grade"].value_counts())

city
Москва             360
Санкт-Петербург    225
Казань             174
Новосибирск        118
Екатеринбург       113
Тверь               92
Пермь               59
Самара              59
Name: count, dtype: int64
grade
10    258
8     258
11    235
7     228
9     221
Name: count, dtype: int64

### Пропуски

В таблицах бывают пустые клетки — **пропуски**. pandas показывает их как `NaN` («not a number», не число).
Пропуск — это *неизвестное* значение, а не ноль: при подсчёте среднего pandas его просто не учитывает,
а сравнение с пропуском всегда даёт `False`.

`isna()` показывает, где стоят пропуски; `isna().sum()` — сколько их в каждом столбце. `fillna(значение)`
заменяет пропуски на указанное значение — чаще всего на медиану или среднее столбца. Чтобы не портить
исходную таблицу, сначала делают копию: `df.copy()`.

In [24]:
print(df.isna().sum())
print(df["math_score"].isna().head())

student_id         0
name               0
grade              0
city               0
math_score        33
python_score      44
hours_per_week     0
average_score      1
dtype: int64
0    False
1    False
2    False
3    False
4     True
Name: math_score, dtype: bool

In [25]:
filled = df.copy()
median_math = filled["math_score"].median()
print("медиана по математике:", median_math)
filled["math_score"] = filled["math_score"].fillna(median_math)
print("пропусков в копии:", filled["math_score"].isna().sum(), "| в исходной таблице:", df["math_score"].isna().sum())

медиана по математике: 66.0
пропусков в копии: 0 | в исходной таблице: 33

### Группировка

`groupby("city")` разбивает таблицу на группы по городу, а следующая команда считает что-то внутри каждой
группы. `mean()` — средний балл по каждому городу, `count()` — сколько заполненных значений в группе.

In [26]:
print(df.groupby("city")["math_score"].mean().round(1))
print(df.groupby("grade")["python_score"].mean().round(1))
print(df.groupby("grade")["math_score"].count())

city
Екатеринбург       64.8
Казань             65.5
Москва             65.0
Новосибирск        65.4
Пермь              69.5
Самара             59.6
Санкт-Петербург    64.6
Тверь              67.0
Name: math_score, dtype: float64
grade
7     64.2
8     64.6
9     67.7
10    71.1
11    72.2
Name: python_score, dtype: float64
grade
7     216
8     253
9     217
10    250
11    231
Name: math_score, dtype: int64

### Вопрос к данным

Теперь можно отвечать на вопросы. Например: в каком классе средний балл по Python самый высокий?
Группируем по классу, считаем среднее, сортируем по убыванию и смотрим первую строку.

In [27]:
by_grade = df.groupby("grade")["python_score"].mean().round(1)
print(by_grade.sort_values(ascending=False).head(1))

grade
11    72.2
Name: python_score, dtype: float64

# Практика

Двадцать коротких задач: десять по NumPy и десять по pandas. Каждая тренирует один приём из занятия.
В ячейке задачи уже есть шаблон функции — замените `...` на решение и запустите ячейку: последняя
строка `test_taskN(taskN)` проверит функцию на нескольких примерах и покажет результат.

Правила общие для всех задач:

- функция **возвращает** результат через `return`, а не печатает его;
- функции для pandas получают таблицу `df` и **не меняют её**: если нужен новый столбец или замена
  пропусков — работайте с копией `df.copy()`;
- `np` и `pd` уже импортированы в начале ноутбука;
- решения — в самом конце, в разделе «Решения». Сначала попробуйте сами.

В примерах к задачам по pandas используется маленькая таблица `small`:

In [28]:
small = pd.DataFrame({
    "student_id": [1, 2, 3],
    "name": ["Аня", "Боря", "Вера"],
    "grade": [7, 8, 7],
    "city": ["Москва", "Казань", "Москва"],
    "math_score": [85.0, np.nan, 72.0],
    "python_score": [78.0, 88.0, 95.0],
    "hours_per_week": [4, 6, 3],
})
small

   student_id  name  grade    city  math_score  python_score  hours_per_week
0           1   Аня      7  Москва        85.0          78.0               4
1           2  Боря      8  Казань         NaN          88.0               6
2           3  Вера      7  Москва        72.0          95.0               3

## NumPy: задачи 1–10

### Задача 1. make_array — массив из списка

Функция получает обычный список чисел. Верните массив NumPy с теми же числами.

**Пример.**

```python
make_array([1, 2, 3])
# array([1, 2, 3])
```

In [ ]:
from tests_numpy_pandas import test_task1

def make_array(numbers):
    ...

test_task1(make_array)

### Задача 2. make_range — числа подряд

Верните массив целых чисел от `start` до `stop`, не включая `stop`. Если `start` равен `stop`, массив пустой.

**Пример.**

```python
make_range(0, 5)
# array([0, 1, 2, 3, 4])
```

In [ ]:
from tests_numpy_pandas import test_task2

def make_range(start, stop):
    ...

test_task2(make_range)

### Задача 3. first_and_last — первый и последний

Функция получает массив хотя бы из одного числа. Верните **кортеж** из первого и последнего элемента. Если в массиве одно число, оба элемента кортежа одинаковые.

**Пример.**

```python
first_and_last(np.array([4, 8, 15, 16]))
# (4, 16)
```

In [ ]:
from tests_numpy_pandas import test_task3

def first_and_last(values):
    ...

test_task3(first_and_last)

### Задача 4. middle_values — середина массива

Верните все элементы массива, кроме первого и последнего. Если элементов два или меньше, результат — пустой массив.

**Пример.**

```python
middle_values(np.array([1, 2, 3, 4, 5]))
# array([2, 3, 4])
```

In [ ]:
from tests_numpy_pandas import test_task4

def middle_values(values):
    ...

test_task4(middle_values)

### Задача 5. increase_scores — прибавить баллы всем

Прибавьте `points` к каждому баллу и верните **новый** массив. Исходный массив менять нельзя.

**Пример.**

```python
increase_scores(np.array([50, 60, 70]), 5)
# array([55, 65, 75])
```

In [ ]:
from tests_numpy_pandas import test_task5

def increase_scores(scores, points):
    ...

test_task5(increase_scores)

### Задача 6. square_numbers — квадраты

Верните массив, в котором каждое число возведено в квадрат.

**Пример.**

```python
square_numbers(np.array([1, -2, 3]))
# array([1, 4, 9])
```

In [ ]:
from tests_numpy_pandas import test_task6

def square_numbers(values):
    ...

test_task6(square_numbers)

### Задача 7. total_score — сумма баллов

Верните сумму всех чисел массива. Для пустого массива сумма равна 0.

**Пример.**

```python
total_score(np.array([10, 20, 30]))
# 60
```

In [ ]:
from tests_numpy_pandas import test_task7

def total_score(scores):
    ...

test_task7(total_score)

### Задача 8. average_score — средний балл

Верните среднее арифметическое чисел массива. В массиве всегда есть хотя бы одно число.

**Пример.**

```python
average_score(np.array([80, 90, 100]))
# 90.0
```

In [ ]:
from tests_numpy_pandas import test_task8

def average_score(scores):
    ...

test_task8(average_score)

### Задача 9. passing_scores — кто прошёл порог

Верните массив только из тех баллов, которые не меньше `threshold`. Порядок сохраняется. Если таких баллов нет, результат — пустой массив.

**Пример.**

```python
passing_scores(np.array([45, 70, 88, 69]), 70)
# array([70, 88])
```

In [ ]:
from tests_numpy_pandas import test_task9

def passing_scores(scores, threshold):
    ...

test_task9(passing_scores)

### Задача 10. subject_means — среднее по предметам

Функция получает двумерный массив: строки — ученики, столбцы — предметы. Верните массив средних баллов по каждому предмету, то есть среднее по столбцам.

**Пример.**

```python
subject_means(np.array([[80, 90],
                        [60, 70]]))
# array([70., 80.])
```

In [ ]:
from tests_numpy_pandas import test_task10

def subject_means(matrix):
    ...

test_task10(subject_means)

## pandas: задачи 11–20

### Задача 11. get_names — один столбец

Верните столбец `name` таблицы — как `Series`.

**Пример.**

```python
get_names(small)
# 0     Аня
# 1    Боря
# 2    Вера
# Name: name, dtype: ...
```

In [ ]:
from tests_numpy_pandas import test_task11

def get_names(df):
    ...

test_task11(get_names)

### Задача 12. get_scores — несколько столбцов

Верните таблицу только из двух столбцов — `math_score` и `python_score`, именно в таком порядке.

**Пример.**

```python
get_scores(small)
#    math_score  python_score
# 0        85.0          78.0
# 1         NaN          88.0
# 2        72.0          95.0
```

In [ ]:
from tests_numpy_pandas import test_task12

def get_scores(df):
    ...

test_task12(get_scores)

### Задача 13. first_students — первые строки

Верните первые `n` строк таблицы. Если `n` больше числа строк — всю таблицу; если `n` равно 0 — пустую таблицу.

**Пример.**

```python
first_students(small, 2)
# строки с номерами 0 и 1 — Аня и Боря
```

In [ ]:
from tests_numpy_pandas import test_task13

def first_students(df, n):
    ...

test_task13(first_students)

### Задача 14. students_in_grade — ученики одного класса

Верните строки учеников из класса `grade`. Номера строк (индексы) оставьте такими же, как в исходной таблице. Если таких учеников нет, получится пустая таблица с теми же столбцами.

**Пример.**

```python
students_in_grade(small, 7)
# строки 0 и 2 — Аня и Вера
```

In [ ]:
from tests_numpy_pandas import test_task14

def students_in_grade(df, grade):
    ...

test_task14(students_in_grade)

### Задача 15. high_math_scores — высокий балл по математике

Верните строки, в которых `math_score` не меньше `threshold`. Строки с пропуском балла в ответ не попадают: сравнение с `NaN` даёт `False`.

**Пример.**

```python
high_math_scores(small, 80)
# строка 0 — Аня (85.0)
```

In [ ]:
from tests_numpy_pandas import test_task15

def high_math_scores(df, threshold):
    ...

test_task15(high_math_scores)

### Задача 16. add_average_score — новый столбец

Верните **копию** таблицы с новым столбцом `average_score` — средним по `math_score` и `python_score` в каждой строке. Если один из баллов пропущен, средним считается оставшийся балл; если пропущены оба — пропуск. Так работает `mean(axis=1)`. Исходную таблицу не меняйте: начните с `df.copy()`.

**Пример.**

```python
add_average_score(small)["average_score"]
# 0    81.5
# 1    88.0   ← математика пропущена, остался балл по Python
# 2    83.5
```

In [ ]:
from tests_numpy_pandas import test_task16

def add_average_score(df):
    ...

test_task16(add_average_score)

### Задача 17. sort_by_python — сортировка

Верните таблицу, отсортированную по `python_score` по убыванию. Строки с пропуском окажутся в конце — так делает pandas сам.

**Пример.**

```python
sort_by_python(small)
# порядок строк: 2 (95.0), 1 (88.0), 0 (78.0)
```

In [ ]:
from tests_numpy_pandas import test_task17

def sort_by_python(df):
    ...

test_task17(sort_by_python)

### Задача 18. students_per_city — сколько учеников в городах

Верните, сколько учеников из каждого города, — результат `value_counts()`: города в индексе, числа — сколько раз встретился город, по убыванию.

**Пример.**

```python
students_per_city(small)
# city
# Москва    2
# Казань    1
```

In [ ]:
from tests_numpy_pandas import test_task18

def students_per_city(df):
    ...

test_task18(students_per_city)

### Задача 19. fill_math_scores — заполнить пропуски

Верните **копию** таблицы, в которой пропуски в `math_score` заменены медианой этого столбца. Остальные столбцы — без изменений. Исходную таблицу не меняйте.

**Пример.**

```python
fill_math_scores(small)["math_score"]
# 0    85.0
# 1    78.5   ← медиана 85.0 и 72.0
# 2    72.0
```

In [ ]:
from tests_numpy_pandas import test_task19

def fill_math_scores(df):
    ...

test_task19(fill_math_scores)

### Задача 20. mean_score_by_grade — среднее по классам

Верните средний балл по математике для каждого класса: `Series`, где индекс — класс (`grade`), а значения — среднее `math_score`. Пропуски при подсчёте среднего pandas не учитывает сам.

**Пример.**

```python
mean_score_by_grade(small)
# grade
# 7    78.5
# 8     NaN   ← у единственного восьмиклассника балл пропущен
```

In [ ]:
from tests_numpy_pandas import test_task20

def mean_score_by_grade(df):
    ...

test_task20(mean_score_by_grade)

# Решения

Один из возможных вариантов решения каждой задачи. Ячейки самодостаточны: каждую можно запустить
и увидеть отчёт проверки.

**Решение 1. make_array.** `np.array` превращает список в массив.

In [ ]:
from tests_numpy_pandas import test_task1

def make_array(numbers):
    return np.array(numbers)

test_task1(make_array)

**Решение 2. make_range.** `np.arange` работает как `range`: правая граница не входит.

In [ ]:
from tests_numpy_pandas import test_task2

def make_range(start, stop):
    return np.arange(start, stop)

test_task2(make_range)

**Решение 3. first_and_last.** Индекс `0` — первый элемент, `-1` — последний; через запятую получается кортеж.

In [ ]:
from tests_numpy_pandas import test_task3

def first_and_last(values):
    return values[0], values[-1]

test_task3(first_and_last)

**Решение 4. middle_values.** Срез `[1:-1]` отрезает первый и последний элементы; для коротких массивов он пустой сам по себе.

In [ ]:
from tests_numpy_pandas import test_task4

def middle_values(values):
    return values[1:-1]

test_task4(middle_values)

**Решение 5. increase_scores.** Сложение с числом создаёт новый массив, исходный не меняется.

In [ ]:
from tests_numpy_pandas import test_task5

def increase_scores(scores, points):
    return scores + points

test_task5(increase_scores)

**Решение 6. square_numbers.** `**` возводит в квадрат каждое число.

In [ ]:
from tests_numpy_pandas import test_task6

def square_numbers(values):
    return values ** 2

test_task6(square_numbers)

**Решение 7. total_score.** `np.sum` пустого массива — 0.

In [ ]:
from tests_numpy_pandas import test_task7

def total_score(scores):
    return np.sum(scores)

test_task7(total_score)

**Решение 8. average_score.** `np.mean` — среднее всех чисел.

In [ ]:
from tests_numpy_pandas import test_task8

def average_score(scores):
    return np.mean(scores)

test_task8(average_score)

**Решение 9. passing_scores.** Маска `scores >= threshold` в квадратных скобках оставляет нужные баллы.

In [ ]:
from tests_numpy_pandas import test_task9

def passing_scores(scores, threshold):
    return scores[scores >= threshold]

test_task9(passing_scores)

**Решение 10. subject_means.** `axis=0` — идём по строкам вниз, получаем по числу на каждый столбец.

In [ ]:
from tests_numpy_pandas import test_task10

def subject_means(matrix):
    return np.mean(matrix, axis=0)

test_task10(subject_means)

**Решение 11. get_names.** Одно имя в скобках — один столбец (Series).

In [ ]:
from tests_numpy_pandas import test_task11

def get_names(df):
    return df["name"]

test_task11(get_names)

**Решение 12. get_scores.** Список имён в скобках — несколько столбцов (DataFrame).

In [ ]:
from tests_numpy_pandas import test_task12

def get_scores(df):
    return df[["math_score", "python_score"]]

test_task12(get_scores)

**Решение 13. first_students.** `iloc[:n]` — строки по номеру; если `n` больше числа строк, вернутся все.

In [ ]:
from tests_numpy_pandas import test_task13

def first_students(df, n):
    return df.iloc[:n]

test_task13(first_students)

**Решение 14. students_in_grade.** Условие даёт маску, маска в скобках оставляет строки.

In [ ]:
from tests_numpy_pandas import test_task14

def students_in_grade(df, grade):
    return df[df["grade"] == grade]

test_task14(students_in_grade)

**Решение 15. high_math_scores.** Сравнение с `NaN` даёт `False`, поэтому пропуски отсеиваются сами.

In [ ]:
from tests_numpy_pandas import test_task15

def high_math_scores(df, threshold):
    return df[df["math_score"] >= threshold]

test_task15(high_math_scores)

**Решение 16. add_average_score.** Сначала `copy()`, затем новый столбец через `mean(axis=1)` — пропуск не считается нулём.

In [ ]:
from tests_numpy_pandas import test_task16

def add_average_score(df):
    result = df.copy()
    result["average_score"] = result[["math_score", "python_score"]].mean(axis=1)
    return result

test_task16(add_average_score)

**Решение 17. sort_by_python.** `sort_values` с `ascending=False`; пропуски pandas ставит в конец.

In [ ]:
from tests_numpy_pandas import test_task17

def sort_by_python(df):
    return df.sort_values("python_score", ascending=False)

test_task17(sort_by_python)

**Решение 18. students_per_city.** `value_counts` считает, сколько раз встретился каждый город.

In [ ]:
from tests_numpy_pandas import test_task18

def students_per_city(df):
    return df["city"].value_counts()

test_task18(students_per_city)

**Решение 19. fill_math_scores.** Медиана считается без пропусков, `fillna` заменяет их на неё — в копии таблицы.

In [ ]:
from tests_numpy_pandas import test_task19

def fill_math_scores(df):
    result = df.copy()
    median = result["math_score"].median()
    result["math_score"] = result["math_score"].fillna(median)
    return result

test_task19(fill_math_scores)

**Решение 20. mean_score_by_grade.** `groupby("grade")` делит таблицу на классы, `mean()` считает среднее в каждом.

In [ ]:
from tests_numpy_pandas import test_task20

def mean_score_by_grade(df):
    return df.groupby("grade")["math_score"].mean()

test_task20(mean_score_by_grade)